version: 0.2 

 

 

 

 

phases: 

  pre_build: 

    commands: 

      - echo Logging in to Amazon ECR... 

      - aws --version 

      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 750733973098.dkr.ecr.ap-southeast-1.amazonaws.com 

      - REPOSITORY_URI= 750733973098.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-task 

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) 

      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}') 

  build: 

    commands: 

      - echo Build started on `date` 

      - echo Building the Docker image... 

      - docker build -t $750733973098.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-task:latest . 

      - docker tag $750733973098.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-task:latest $750733973098.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-task:$IMAGE_TAG 

  post_build: 

    commands: 

      - echo Build completed on `date` 

      - echo Pushing the Docker images... 

      - docker push $750733973098.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-task:latest 

      - docker push $750733973098.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-task:$IMAGE_TAG 

      - echo Writing image definitions file... 

      - printf '[{"name":"ecr-task","imageUri":"%s"}]' $REPOSITORY_U 

 
